import pptxgen from 'pptxgenjs'
import path from 'path'
import fs from 'fs'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const COLORS = {
  primary: '2563EB',
  secondary: '0F172A',
  text: '1E293B',
  border: 'E2E8F0',
  white: 'FFFFFF',
  muted: '94A3B8',
  accent: '3B82F6'
}

export const generatePPt = async (data) => {
  const ppt = new pptxgen()
  ppt.layout = 'LAYOUT_WIDE'
  ppt.author = 'AuraMind AI'
  ppt.title = data.title || 'Presentation'
  ppt.subject = data.subtitle || data.title || 'Generated by AuraMind AI'
  ppt.company = 'AuraMind AI'

  addCover(ppt, data)

  const slides = Array.isArray(data.slides) ? data.slides : []
  slides.forEach((s, i) => {
    addContentSlide(ppt, s.title, s.points || [], i + 1, slides.length)
  })

  addThankYou(ppt)

  const tempDir = path.join(__dirname, '../temp')
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true })
  }

  const filename = `Presentation-${Date.now()}.pptx`
  const filePath = path.join(tempDir, filename)
  await ppt.writeFile({ fileName: filePath })

  return { filename, filePath }
}

const addCover = (ppt, data) => {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.secondary }

  // Title
  slide.addText(data.title || 'Presentation Title', {
    x: 0.8,
    y: 2.0,
    w: 11.7,
    h: 1.6,
    fontSize: 34,
    bold: true,
    color: COLORS.white,
    align: 'center',
    valign: 'middle'
  })

  // Subtitle
  if (data.subtitle) {
    slide.addText(data.subtitle, {
      x: 0.8,
      y: 3.8,
      w: 11.7,
      h: 0.8,
      fontSize: 18,
      color: '93C5FD',
      align: 'center',
      valign: 'top'
    })
  }

  // Footer Branding
  slide.addText('⚡ Generated by AuraMind AI', {
    x: 0.8,
    y: 6.6,
    w: 11.7,
    h: 0.4,
    fontSize: 11,
    color: '64748B',
    align: 'center'
  })
}

const addContentSlide = (ppt, title, points, page, total) => {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.white }

  // Slide Title
  slide.addText(title || `Slide ${page}`, {
    x: 0.8,
    y: 0.6,
    w: 11.7,
    h: 0.8,
    fontSize: 24,
    bold: true,
    color: COLORS.secondary
  })

  // Native PowerPoint Paragraph Bullets with Bold Lead-in Keywords
  const cleanPoints = (Array.isArray(points) ? points : []).slice(0, 6)
  
  if (cleanPoints.length > 0) {
    const textObjects = []

    cleanPoints.forEach((pt, idx) => {
      const match = String(pt || '').match(/^\*\*([^*]+)\*\*:\s*(.*)$/)
      const isLast = idx === cleanPoints.length - 1

      if (match) {
        textObjects.push({
          text: `${match[1]}: `,
          options: {
            bullet: true,
            bold: true,
            fontSize: 16,
            color: COLORS.secondary
          }
        })
        textObjects.push({
          text: match[2],
          options: {
            bullet: false,
            bold: false,
            breakLine: !isLast,
            fontSize: 16,
            color: COLORS.text,
            lineSpacingMultiple: 1.35
          }
        })
      } else {
        textObjects.push({
          text: String(pt || '').replace(/\*\*/g, ''),
          options: {
            bullet: true,
            bold: false,
            breakLine: !isLast,
            fontSize: 16,
            color: COLORS.text,
            lineSpacingMultiple: 1.35
          }
        })
      }
    })

    slide.addText(textObjects, {
      x: 0.8,
      y: 1.6,
      w: 11.7,
      h: 4.8,
      valign: 'top'
    })
  }

  // Slide Footer
  slide.addText('AuraMind AI', {
    x: 0.8,
    y: 6.8,
    w: 3.0,
    h: 0.3,
    fontSize: 10,
    color: COLORS.muted
  })

  slide.addText(`${page} / ${total}`, {
    x: 9.5,
    y: 6.8,
    w: 3.0,
    h: 0.3,
    align: 'right',
    fontSize: 10,
    color: COLORS.muted
  })
}

const addThankYou = (ppt) => {
  const slide = ppt.addSlide()
  slide.background = { color: COLORS.secondary }

  slide.addText('Thank You', {
    x: 0.8,
    y: 2.4,
    w: 11.7,
    h: 1.2,
    align: 'center',
    valign: 'middle',
    color: COLORS.white,
    fontSize: 38,
    bold: true
  })

  slide.addText('⚡ Created with AuraMind AI Multi-Agent Platform', {
    x: 0.8,
    y: 3.8,
    w: 11.7,
    h: 0.6,
    align: 'center',
    color: '93C5FD',
    fontSize: 16
  })
}
