import PDFDocument from "pdfkit";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const tempDir = path.join(__dirname, "../temp");
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    const filename = `Document-${Date.now()}.pdf`;
    const filePath = path.join(tempDir, filename);
    const writeStream = fs.createWriteStream(filePath);

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "AuraMind AI",
        Title: data.title || "Document",
        Creator: "AuraMind AI",
      },
    });

    doc.pipe(writeStream);
    writeStream.on("finish", () => resolve({ filename, filePath }));
    writeStream.on("error", reject);
    doc.on("error", reject);

    // Title
    doc
      .fillColor("#111827")
      .fontSize(28)
      .text(data.title, {
        align: "center",
      });

    if (data.subtitle) {
      doc.moveDown(0.5);

      doc
        .fillColor("#6B7280")
        .fontSize(12)
        .text(data.subtitle, {
          align: "center",
        });

      doc.moveDown(2);
    }

    data.sections?.forEach((section) => {
      doc
        .fillColor("#111827")
        .fontSize(18)
        .text(section.heading);

      doc.moveDown(0.5);

      section.points?.forEach((point) => {
        doc
          .fillColor("#374151")
          .fontSize(12)
          .text(`• ${point}`, {
            lineGap: 5,
          });
      });

      doc.moveDown();
    });

    doc.moveDown();

    doc
      .fillColor("#6B7280")
      .fontSize(10)
      .text("Generated by AuraMind AI", {
        align: "center",
      });

    doc.end();
  });
};